### ISSUE TITLE
Todo-Liste für Release 1.0

### ISSUE THREAD

**Issue by Art4** [youthweb/bbcode-parser#1]
Bevor Release 1.0 erscheinen kann, sind folgende Dinge zu erledigen:
- [x] Unittests mit PHPUnit schreiben
- [x] Unittests mit Travis-CI automatisch testen lassen
- [x] Code Coverage mit http://coveralls.io ermitteln lassen
- [x] Eine Code Coverage von mindestens 80% erreichen
- [x] Doku über die Anwendung und Konfiguration schreiben

**Comment by Art4** [comment]
Release 1.0.0 wurde eben veröffentlicht.
